### ISSUE TITLE
fixed mnemonics are not being used

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-3-proposals#136]
This `agd keys add` is missing the `--recover` option:

https://github.com/Agoric/agoric-3-proposals/blob/ed0faf911e5972f660f7480b1ee1d611e598517a/packages/synthetic-chain/public/upgrade-test-scripts/run_prepare_zero.sh#L16

cc @turadg @LuqiPan @ivanlei

**Comment by gacogo** [comment]
@dckc the command is ```agd keys export user1 --unsafe   --unarmored-hex --keyring-backend="test" ```to export private keys
