### ISSUE TITLE
Should a3p support unvalidated empty `upgradeInfo`?

### ISSUE THREAD

**Issue by gibson042** [Agoric/agoric-3-proposals#146]
In reviewing the release process with @mhofman, we observed that `"upgradeInfo": {}` in [agoric-sdk branch `agoric-upgrade-14` a3p-integration/proposals/a:upgrade-14/package.json](https://github.com/Agoric/agoric-sdk/blob/agoric-upgrade-14/a3p-integration/proposals/a%3Aupgrade-14/package.json#L6) (and more generally in all agoric-sdk release commit a3p-integration/proposals/*/package.json files) seems to be invalid because it does not reference a location for the necessary archives. The containing `agoricProposal` object should probably include a property indicating to agoric-3-proposals that the corresponding `agd tx gov submit-proposal software-upgrade` should include a [`--no-validate` option](https://github.com/agoric-labs/cosmos-sdk/blob/1206d21b7e6be6de5ad1edf113f6530ac604f5d4/x/upgrade/client/cli/tx.go#L57), which means that agoric-3-proposals should support (and document support for) such configuration.

@mhofman , please correct anything I've gotten wrong in the above description.

**Comment by ivanlei** [comment]
@gibson042 
> we've actually already taken on --no-validate for dev-upgrade-15
