### ISSUE TITLE
killAgd does not work cross shell

### ISSUE THREAD

**Issue by mhofman** [Agoric/agoric-3-proposals#162]
A proposal test script may need to killAgd and restart it. However the agd process was started and another shell running concurrently when in tests.

Instead of `wait $AGD_PID` do `tail --pid=$AGD_PID -f /dev/null` as seen in https://stackoverflow.com/a/41613532

While it polls using `kill -0` internally, it easier than writing that ourselves

**Comment by gibson042** [comment]
Fixed by #164; I didn't check for this issue before merging it.
