### ISSUE TITLE
Migrate agoric-upgrade-16av to agoric-3-proposals

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-3-proposals#171]
## What is the Problem Being Solved?

When a new proposal passes for mainNet, we move tests from [a3p-integration](https://github.com/Agoric/agoric-sdk/tree/master/a3p-integration) into [agoric-3-proposals](https://github.com/Agoric/agoric-3-proposals). [Proposal 76](https://agoric.explorers.guru/proposal/76) is expected to pass tomorrow.

## Description of the Design

Move the tests over, and move re-usable code into synthetic-chain library.

## Security Considerations

None

## Scaling Considerations

None

## Test Plan

Ensure a-3-p tests run.

## Upgrade Considerations

The job's not done until the clean-up is complete.

**Comment by mhofman** [comment]
Is there an issue for upgrading agoric-sdk  to use this new image and no longer pass the core eval as first step?

**Comment by Chris-Hibbert** [comment]
> Is there an issue for upgrading agoric-sdk to use this new image and no longer pass the core eval as first step?

My next step is [10053](https://github.com/Agoric/agoric-sdk/pull/10053). If that doesn't do everything that's needed, please let me know. I'm also preparing an updated to [CONTRIBUTING.md](https://github.com/Agoric/agoric-3-proposals/blob/main/CONTRIBUTING.md) to add what I know of the process, so more info would be appreciated.
