### ISSUE TITLE
build and push a 'use' image for each proposal

### ISSUE THREAD

**Issue by turadg** [Agoric/agoric-3-proposals#25]
# Problem to solve
Downstream integration tests rely on a synthetic state of Mainnet. For example, the upgrade-12 test in agoric-sdk. 

While developing, it needs a branch that reflects the complete history of passed proposals. This repo publishes that as `main` (since https://github.com/Agoric/agoric-3-proposals/pull/24) 

However, once upgrade-12 itself passes and is _incorporated_ into `main`, that test will begin to fail. Even though the proposal is done and passed, we shouldn't break the CI of the branch that tested it.

# Design

So this repo should publish an image for using the chain after each proposal. (i.e. an image for each `use-${proposalName}` stage)

There should still be a `main` image because all the "use" images have a RUN that terminates (for use in tests) but we want to offer an image that developers can use to run the chain with the latest synthetic state of Mainnet.

**Comment by mhofman** [comment]
I am currently working around this by manually creating an `upgrade-12` branch (and later `upgrade-13`) containing only the required layers, and using GH actions trigger to generate a tagged image.
