### ISSUE TITLE
publish an image of all passed proposals

### ISSUE THREAD

**Issue by turadg** [Agoric/agoric-3-proposals#6]
## What is the Problem Being Solved?

We need a way to test the impending upgrade handler from agoric-sdk on top of the agoric-3 chain.

When this test was in agoric-sdk, its final step was to perform the next (unreleased) upgrade. To do that in this repo, it would have to pull an SDK image with the version of agd to test. But that would make the testing cycle laborious when making edits in agoric-sdk and checking they succeed at upgrade.

## Description of the Design

Have this repo publish an image with the state resulting from all passed proposals.

Agoric-sdk will pull that image for its own CI, in which it applies the unreleased upgrade handler on top. 

To facilitate external use, also,
- https://github.com/Agoric/agoric-3-proposals/issues/5

## Upgrade Considerations

**Comment by dckc** [comment]
hm. where do we document `docker pull ghcr.io/agoric/agoric-3-proposals:main`?

**Comment by turadg** [comment]
> where do we document

https://github.com/Agoric/agoric-3-proposals/pull/13/commits/9823dd4637691bc6d08fa562624719b80c890bcb but it's not yet in main. 

I'll include it in my next PR
