### ISSUE TITLE
crabble went to mainnet in proposal 64

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-3-proposals#62]
should move from c: to 64:

https://github.com/Agoric/agoric-3-proposals/blob/5d6ba276a25004f35ce37b02491131e1259f1e26/proposals/c%3Acrabble-start/use.sh#L8

for ref: https://agoric.explorers.guru/proposal/64

**Comment by mhofman** [comment]
I would like this to be addressed soon so that the upgrade-14 tests can more closely represent what will happen on mainnet.
