### ISSUE TITLE
can't use cosgov with synthetic-chain - ports not exposed

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-3-proposals#71]
I encouraged @Chris-Hibbert to use cosgov.org to run a quick core-eval script, but his browser got "connection refused" when trying to reach agd; `curl` gave the same symptoms.
`docker ps` showed the ports not exposed. I asked how he started his container, and he said with `synthetic-chain`.

Contrast with

https://github.com/Agoric/dapp-offer-up/blob/853c415d17763703c04627b2cded7b46c2799d67/docker-compose.yml#L9-L12

There are risks around exposing ports, so it should perhaps be optional.

cc @turadg

**Comment by turadg** [comment]
I use this,
```
docker run -d -p 26657:26657 -p 1317:1317 -p 9090:9090 ghcr.io/agoric/agoric-3-proposals:latest
```

We could make the `test --debug` option expose the ports the same way for local testing.

**Comment by turadg** [comment]
> There are risks around exposing ports, so it should perhaps be optional.

What are the risks? These are synthetic chains.

I think we could just have them always exposed by adding,
```
EXPOSE 1317 9090 26657
```

**Comment by dckc** [comment]
> What are the risks? These are synthetic chains.

yeah; not worth bothering about

**Comment by turadg** [comment]
turns out the ports were already exposed (which makes sense or the command above shouldn't have worked)
```
docker inspect --format='{{.Config.ExposedPorts}}' ghcr.io/agoric/agoric-3-proposals:use-upgrade-8
map[1317/tcp:{} 26657/tcp:{} 9090/tcp:{}]
```
There's no way to have the image specify ports to bind in a container. The `--publish-all` option can publish them all, but they'll be to random ports on the host. So I don't see any way around the `--port` list on the CLI. I'll add that to the `--debug` mode and README for downstream uses.

**Comment by dckc** [comment]
I neglected to verify that cosgov works when reviewing #150. I wonder if I approved it too soon. https://github.com/Agoric/agoric-sdk/issues/9052 seems to say that some CORS stuff is needed too.

**Comment by turadg** [comment]
I had tested #150 before merging and just confirmed it's still working as documented: https://github.com/Agoric/agoric-3-proposals/pull/150/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

@dckc I'll assign this issue to you to do with as you see fit.

**Comment by dckc** [comment]
d'oh! **Network not connected.** means: "you didn't make a choice from the network menu"

tee hee.
