### ISSUE TITLE
builds running out of disk space

### ISSUE THREAD

**Issue by turadg** [Agoric/agoric-3-proposals#78]
https://github.com/Agoric/agoric-3-proposals/pull/59 and https://github.com/Agoric/agoric-3-proposals/pull/75 are consistently failing due to disk space.

Errors like,
```
      # ERROR: failed to copy files: userspace copy failed: write /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/336/fs/root/.agoric/data/ag-cosmos-chain-state/flight-recorder.bin: no space left on device
```

Some resources,
- https://www.baeldung.com/linux/docker-fix-no-space-error
- https://github.com/marketplace/actions/maximize-build-disk-space

**Comment by mhofman** [comment]
Oh we should disable the flight recorder when building layers, or at least nuke it before finalizing the layer
